### PR TITLE
Modifying user data for support key

### PR DESCRIPTION
**Pull request by hmunfru**
@jframos

### CODE REVIEW

**Comment by flopezag** [comment]
Travis error...

**Comment by jframos** [comment]
From our private Jenkins it works fine... Could it be a connection problem?

**Comment by flopezag** [comment]
How I could see it is related to the maven repository that we are using, or I mix other PR.

**Comment by jesuspg** [comment]
it was a problem in nexus! fixed! :+1:

**Comment by jframos** [comment]
LGTM

**Pull request merged**
