### PR TITLE
Bug/4893 requests keystone

### PR DESCRIPTION
**Pull request by jesuspg**
@hmunfru @jframos 

(please test in exp. environment)

### CODE REVIEW

**Comment by jesuspg** [comment]
jenkins job (PaaSManager-Acceptance-comp) was launched with result: no failures

**Comment by hmunfru** [comment]
LGTM

**Comment by flopezag** [comment]
I see that it is urgent but taking into account the problem I suggest to translate the 200 and 201 to a static variable and resolve the magic numbers.

**Comment by jesuspg** [comment]
@flopezag fixed in commit: change 59e1945

**Comment by jframos** [comment]
LGTM

**Comment by flopezag** [comment]
LGTM

**Pull request merged**
